[package]
name = "renk"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
dotenv = "0.15"
